# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 461c9fb9af63aa4321edf5577a13623dce9ab01b67548fa1c7a83c8155859630b3f0a29dda130d2bd3dc45ba2ee608665ffbf3a54b41f42f72200cfbe791f907

test:
  secret_key_base: e1b5dbbd1280467b3cc8613c6875e1fb095b9adf7bfc2960530e962eab27aacdcccbbb6f0eb749162e38a024165a0de71500f7839dafb562e0b961cacdab6441

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
